CREATE OR REPLACE VIEW DEV_QUEBECTECH.UTIL.V_REGISTRY_CURRENT_NAME AS
WITH n AS (
  SELECT
    NEQ,
    NOM_ASSUJ,
    DAT_INIT_NOM_ASSUJ,
    DAT_FIN_NOM_ASSUJ,
    ROW_NUMBER() OVER (
      PARTITION BY NEQ
      ORDER BY
        -- prefer current name (no end date), otherwise most recent init date
        IFF(DAT_FIN_NOM_ASSUJ IS NULL, 0, 1),
        DAT_INIT_NOM_ASSUJ DESC
    ) AS RN
  FROM DEV_DATAMART.ENTREPRISES_DU_QUEBEC.REGISTRE_NOMS
)
SELECT
  NEQ                                                   AS REG_NEQ_RAW,
  UTIL.NORM_NEQ(NEQ)                                    AS REG_NEQ_NORM,
  NOM_ASSUJ                                             AS REG_NAME_RAW,
  UTIL.NORM_NAME(NOM_ASSUJ)                             AS REG_NAME_NORM,
  DAT_INIT_NOM_ASSUJ,
  DAT_FIN_NOM_ASSUJ
FROM n
WHERE RN = 1;

CREATE OR REPLACE VIEW DEV_QUEBECTECH.UTIL.V_REGISTRY_ACTIVE AS
SELECT
  NEQ                                                   AS REG_NEQ_RAW,
  UTIL.NORM_NEQ(NEQ)                                    AS REG_NEQ_NORM,
  DATE_IMMATRICULATION,
  FORME_JURIDIQUE,
  SECTEUR_ACTIVITE_PRINCIPAL,
  SECTEUR_ACTIVITE_SECONDAIRE,
  N_EMPLOYES,
  ANNEE_DERNIERE_PRODUCTION_DECLARATION_IMPOT
FROM DEV_DATAMART.ENTREPRISES_DU_QUEBEC.ENTREPRISES_EN_FONCTION;
