USE DATABASE DEV_QUEBECTECH;

-- 0) Dealroom standardized
CREATE OR REPLACE TEMP TABLE TMP_DRM_STD AS
SELECT
  DEALROOM_ID,
  NAME AS DRM_NAME,
  TRADE_REGISTER_NUMBER AS DRM_TRADE_REGISTER_NUMBER,
  NULLIF(REGEXP_REPLACE(TRADE_REGISTER_NUMBER, '[^0-9]', ''), '') AS DRM_NEQ_DIGITS,
  CASE
    WHEN NULLIF(REGEXP_REPLACE(TRADE_REGISTER_NUMBER, '[^0-9]', ''), '') IS NULL THEN NULL
    WHEN LENGTH(NULLIF(REGEXP_REPLACE(TRADE_REGISTER_NUMBER, '[^0-9]', ''), '')) >= 10
      THEN LEFT(NULLIF(REGEXP_REPLACE(TRADE_REGISTER_NUMBER, '[^0-9]', ''), ''), 10)
    ELSE NULLIF(REGEXP_REPLACE(TRADE_REGISTER_NUMBER, '[^0-9]', ''), '')
  END AS DRM_NEQ_CLEAN,

  TRIM(
    REGEXP_REPLACE(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          UPPER(REPLACE(COALESCE(NAME,''), '&', ' AND ')),
          '[^A-Z0-9 ]', ' '
        ),
        '\\s+', ' '
      ),
      '\\b(INC|INCORPORATED|CORP|CORPORATION|LTD|LIMITED|LTÉE|LTEE|SAS|S\\.A\\.S|SENC|S\\.E\\.N\\.C|SENCRL|S\\.E\\.N\\.C\\.R\\.L|LP|LLP|CO|COMPANY|COMPAGNIE|GROUPE|GROUP)\\b',
      ''
    )
  ) AS DRM_NAME_STD,

  LEFT(
    TRIM(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          REGEXP_REPLACE(
            UPPER(REPLACE(COALESCE(NAME,''), '&', ' AND ')),
            '[^A-Z0-9 ]', ' '
          ),
          '\\s+', ' '
        ),
        '\\b(INC|INCORPORATED|CORP|CORPORATION|LTD|LIMITED|LTÉE|LTEE|SAS|S\\.A\\.S|SENC|S\\.E\\.N\\.C|SENCRL|S\\.E\\.N\\.C\\.R\\.L|LP|LLP|CO|COMPANY|COMPAGNIE|GROUPE|GROUP)\\b',
        ''
      )
    ),
    4
  ) AS DRM_LEFT4,

  SOUNDEX(
    TRIM(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          REGEXP_REPLACE(
            UPPER(REPLACE(COALESCE(NAME,''), '&', ' AND ')),
            '[^A-Z0-9 ]', ' '
          ),
          '\\s+', ' '
        ),
        '\\b(INC|INCORPORATED|CORP|CORPORATION|LTD|LIMITED|LTÉE|LTEE|SAS|S\\.A\\.S|SENC|S\\.E\\.N\\.C|SENCRL|S\\.E\\.N\\.C\\.R\\.L|LP|LLP|CO|COMPANY|COMPAGNIE|GROUPE|GROUP)\\b',
        ''
      )
    )
  ) AS DRM_SOUNDEX
FROM DEV_QUEBECTECH.BRONZE.DRM_COMPANY_BRONZE;

-- 1) Registry names standardized (START WITH ACTIVE ONLY to go fast)
CREATE OR REPLACE TEMP TABLE TMP_REG_NAMES_STD AS
SELECT
  NEQ,
  NOM_ASSUJ,
  STATUT,
  TRIM(
    REGEXP_REPLACE(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          UPPER(REPLACE(COALESCE(NOM_ASSUJ,''), '&', ' AND ')),
          '[^A-Z0-9 ]', ' '
        ),
        '\\s+', ' '
      ),
      '\\b(INC|INCORPORATED|CORP|CORPORATION|LTD|LIMITED|LTÉE|LTEE|SAS|S\\.A\\.S|SENC|S\\.E\\.N\\.C|SENCRL|S\\.E\\.N\\.C\\.R\\.L|LP|LLP|CO|COMPANY|COMPAGNIE|GROUPE|GROUP)\\b',
      ''
    )
  ) AS REG_NAME_STD,
  LEFT(
    TRIM(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          REGEXP_REPLACE(
            UPPER(REPLACE(COALESCE(NOM_ASSUJ,''), '&', ' AND ')),
            '[^A-Z0-9 ]', ' '
          ),
          '\\s+', ' '
        ),
        '\\b(INC|INCORPORATED|CORP|CORPORATION|LTD|LIMITED|LTÉE|LTEE|SAS|S\\.A\\.S|SENC|S\\.E\\.N\\.C|SENCRL|S\\.E\\.N\\.C\\.R\\.L|LP|LLP|CO|COMPANY|COMPAGNIE|GROUPE|GROUP)\\b',
        ''
      )
    ),
    4
  ) AS REG_LEFT4,
  SOUNDEX(
    TRIM(
      REGEXP_REPLACE(
        REGEXP_REPLACE(
          REGEXP_REPLACE(
            UPPER(REPLACE(COALESCE(NOM_ASSUJ,''), '&', ' AND ')),
            '[^A-Z0-9 ]', ' '
          ),
          '\\s+', ' '
        ),
        '\\b(INC|INCORPORATED|CORP|CORPORATION|LTD|LIMITED|LTÉE|LTEE|SAS|S\\.A\\.S|SENC|S\\.E\\.N\\.C|SENCRL|S\\.E\\.N\\.C\\.R\\.L|LP|LLP|CO|COMPANY|COMPAGNIE|GROUPE|GROUP)\\b',
        ''
      )
    )
  ) AS REG_SOUNDEX
FROM DEV_DATAMART.ENTREPRISES_DU_QUEBEC.REGISTRE_NOMS
WHERE STATUT = 'En vigueur'
  AND NOM_ASSUJ IS NOT NULL;

-- 2) Number matches (cheap)
CREATE OR REPLACE TEMP TABLE TMP_MATCH_NUMBER AS
SELECT
  d.DEALROOM_ID,
  d.DRM_NEQ_CLEAN AS NEQ_NUMBER_MATCH
FROM TMP_DRM_STD d
JOIN DEV_DATAMART.ENTREPRISES_DU_QUEBEC.ENTREPRISES_EN_FONCTION r
  ON r.NEQ = d.DRM_NEQ_CLEAN
WHERE d.DRM_NEQ_CLEAN IS NOT NULL;

-- 3) Only name-match those NOT already matched by number
CREATE OR REPLACE TEMP TABLE TMP_DRM_NEEDS_NAME AS
SELECT d.*
FROM TMP_DRM_STD d
LEFT JOIN TMP_MATCH_NUMBER n
  ON n.DEALROOM_ID = d.DEALROOM_ID
WHERE n.DEALROOM_ID IS NULL
  AND d.DRM_NAME_STD IS NOT NULL
  AND d.DRM_NAME_STD <> '';

-- 4) Candidate pairs via UNION ALL (no OR join)
CREATE OR REPLACE TEMP TABLE TMP_NAME_CANDIDATES AS
SELECT
  d.DEALROOM_ID,
  r.NEQ AS NEQ_NAME_CANDIDATE,
  r.NOM_ASSUJ AS REG_NAME_RAW,
  r.STATUT AS REG_NAME_STATUS,
  d.DRM_NAME_STD,
  r.REG_NAME_STD,
  JAROWINKLER_SIMILARITY(d.DRM_NAME_STD, r.REG_NAME_STD) AS NAME_SIM
FROM TMP_DRM_NEEDS_NAME d
JOIN TMP_REG_NAMES_STD r
  ON d.DRM_LEFT4 = r.REG_LEFT4

UNION ALL

SELECT
  d.DEALROOM_ID,
  r.NEQ AS NEQ_NAME_CANDIDATE,
  r.NOM_ASSUJ AS REG_NAME_RAW,
  r.STATUT AS REG_NAME_STATUS,
  d.DRM_NAME_STD,
  r.REG_NAME_STD,
  JAROWINKLER_SIMILARITY(d.DRM_NAME_STD, r.REG_NAME_STD) AS NAME_SIM
FROM TMP_DRM_NEEDS_NAME d
JOIN TMP_REG_NAMES_STD r
  ON d.DRM_SOUNDEX = r.REG_SOUNDEX;

-- 5) Keep only good candidates + pick the best per Dealroom
-- 5) Keep only good candidates + pick the best per Dealroom (NO nested windows)
CREATE OR REPLACE TEMP TABLE TMP_BEST_NAME_MATCH AS
WITH scored AS (
  SELECT
    c.*,
    MAX(NAME_SIM) OVER (PARTITION BY DEALROOM_ID) AS TOP_SIM
  FROM TMP_NAME_CANDIDATES c
  WHERE NAME_SIM >= 88
),
scored2 AS (
  SELECT
    s.*,
    COUNT_IF(NAME_SIM >= TOP_SIM - 1) OVER (PARTITION BY DEALROOM_ID) AS N_NEAR_TOP
  FROM scored s
)
SELECT
  DEALROOM_ID,
  NEQ_NAME_CANDIDATE AS NEQ_NAME_MATCH,
  REG_NAME_RAW,
  REG_NAME_STATUS,
  NAME_SIM,

  CASE
    WHEN DRM_NAME_STD = REG_NAME_STD THEN 'perfect'
    WHEN NAME_SIM >= 95 THEN 'strong'
    WHEN NAME_SIM >= 90 THEN 'weak'
    ELSE 'none'
  END AS NAME_MATCH_QUALITY,

  IFF(TOP_SIM >= 95 AND N_NEAR_TOP >= 2, 1, 0) AS FLAG_NAME_MATCH_AMBIGUOUS
FROM scored2
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY DEALROOM_ID
  ORDER BY NAME_SIM DESC
) = 1;


-- 6) Build final bridge table (same logic as before, but now it’s fast)
CREATE OR REPLACE TABLE DEV_QUEBECTECH.SILVER.DRM_REGISTRY_BRIDGE_SILVER AS
WITH reg_addr AS (
  SELECT
    NEQ,
    LISTAGG(DISTINCT ADRESSE, ' | ') WITHIN GROUP (ORDER BY ADRESSE) AS REGISTRY_ADDRESSES
  FROM DEV_DATAMART.ENTREPRISES_DU_QUEBEC.REGISTRE_ADRESSES
  GROUP BY 1
),
combined AS (
  SELECT
    d.DEALROOM_ID,
    d.DRM_NAME,
    d.DRM_TRADE_REGISTER_NUMBER,
    d.DRM_NEQ_CLEAN,

    n.NEQ_NUMBER_MATCH,
    nm.NEQ_NAME_MATCH,
    nm.REG_NAME_RAW,
    nm.REG_NAME_STATUS,
    nm.NAME_SIM,
    nm.NAME_MATCH_QUALITY,
    nm.FLAG_NAME_MATCH_AMBIGUOUS,

    COALESCE(n.NEQ_NUMBER_MATCH, nm.NEQ_NAME_MATCH) AS NEQ_FINAL,

    CASE
      WHEN n.NEQ_NUMBER_MATCH IS NOT NULL THEN 'number'
      WHEN nm.NEQ_NAME_MATCH IS NOT NULL THEN 'name'
      ELSE NULL
    END AS MATCH_SOURCE,

    IFF(
      n.NEQ_NUMBER_MATCH IS NOT NULL
      AND nm.NEQ_NAME_MATCH IS NOT NULL
      AND n.NEQ_NUMBER_MATCH <> nm.NEQ_NAME_MATCH,
      1, 0
    ) AS FLAG_NEQ_NAME_CONFLICT,

    IFF(
      d.DRM_NEQ_CLEAN IS NOT NULL
      AND n.NEQ_NUMBER_MATCH IS NULL,
      1, 0
    ) AS FLAG_NUMBER_NOT_FOUND_IN_REGISTRY
  FROM TMP_DRM_STD d
  LEFT JOIN TMP_MATCH_NUMBER n
    ON n.DEALROOM_ID = d.DEALROOM_ID
  LEFT JOIN TMP_BEST_NAME_MATCH nm
    ON nm.DEALROOM_ID = d.DEALROOM_ID
)
SELECT
  c.*,
  ra.DATE_IMMATRICULATION,
  ra.ANNEE_DERNIERE_PRODUCTION_DECLARATION_IMPOT,
  ra.N_EMPLOYES,
  ad.REGISTRY_ADDRESSES,
  IFF(
    c.NEQ_FINAL IS NOT NULL
    AND COUNT(*) OVER (PARTITION BY c.NEQ_FINAL) > 1,
    1, 0
  ) AS FLAG_MULTIPLE_DEALROOM_SAME_NEQ
FROM combined c
LEFT JOIN DEV_DATAMART.ENTREPRISES_DU_QUEBEC.ENTREPRISES_EN_FONCTION ra
  ON ra.NEQ = c.NEQ_FINAL
LEFT JOIN reg_addr ad
  ON ad.NEQ = c.NEQ_FINAL;


SELECT
  COUNT(*)                                                   AS N_DEALROOM_TOTAL,

  COUNT_IF(NEQ_FINAL IS NOT NULL)                             AS N_MATCHED_ANY,
  COUNT_IF(NEQ_FINAL IS NULL)                                 AS N_UNMATCHED,

  COUNT_IF(MATCH_SOURCE = 'number')                           AS N_MATCHED_BY_NUMBER,
  COUNT_IF(MATCH_SOURCE = 'name')                             AS N_MATCHED_BY_NAME,

  COUNT_IF(NEQ_NUMBER_MATCH IS NOT NULL)                      AS N_HAS_VALID_NUMBER_MATCH,
  COUNT_IF(NEQ_NAME_MATCH IS NOT NULL)                        AS N_HAS_NAME_MATCH,

  /* Issues */
  COUNT_IF(FLAG_NEQ_NAME_CONFLICT = 1)                        AS N_ISSUE_NEQ_NAME_CONFLICT,
  COUNT_IF(FLAG_MULTIPLE_DEALROOM_SAME_NEQ = 1)               AS N_ISSUE_MULTI_DEALROOM_SAME_NEQ,
  COUNT_IF(FLAG_NUMBER_NOT_FOUND_IN_REGISTRY = 1)             AS N_ISSUE_NUMBER_NOT_FOUND,
  COUNT_IF(FLAG_NAME_MATCH_AMBIGUOUS = 1)                     AS N_ISSUE_NAME_AMBIGUOUS,

  /* Helpful rates */
  ROUND(100 * COUNT_IF(NEQ_FINAL IS NOT NULL) / NULLIF(COUNT(*),0), 2) AS PCT_MATCHED_ANY,
  ROUND(100 * COUNT_IF(MATCH_SOURCE = 'number') / NULLIF(COUNT(*),0), 2) AS PCT_MATCHED_BY_NUMBER,
  ROUND(100 * COUNT_IF(MATCH_SOURCE = 'name') / NULLIF(COUNT(*),0), 2)   AS PCT_MATCHED_BY_NAME
FROM DEV_QUEBECTECH.SILVER.DRM_REGISTRY_BRIDGE_SILVER;
