CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES AS
SELECT
  DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ)                 AS REQ_NEQ,
  NOM_ASSUJ                                         AS REQ_NAME_RAW,
  DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ)          AS REQ_NAME_NORM,
  SPLIT_PART(DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ), ' ', 1) AS REQ_TOK1,
  LEFT(DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ), 4) AS REQ_P4
FROM DEV_DATAMART.ENTREPRISES_DU_QUEBEC.REGISTRE_NOMS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ)
  ORDER BY IFF(DAT_FIN_NOM_ASSUJ IS NULL, 0, 1), DAT_INIT_NOM_ASSUJ DESC
) = 1
AND DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ) IS NOT NULL
AND DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ) IS NOT NULL;

-- Helps the blocker joins
ALTER TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES CLUSTER BY (REQ_P4, REQ_TOK1, REQ_NEQ);



CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_COMPANY_KEYS AS
SELECT
  SRC,
  SRC_ID,
  NEQ_NORM,
  DOMAIN_NORM,
  LINKEDIN_NORM,
  NAME_NORM,
  TOK1,
  P4
FROM DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM;



CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ AS
SELECT
  k.SRC, k.SRC_ID,
  r.REQ_NEQ,
  'REQ_NEQ' AS MATCH_TYPE,
  1.0::FLOAT AS SCORE
FROM DEV_QUEBECTECH.UTIL.T_COMPANY_KEYS k
JOIN DEV_QUEBECTECH.UTIL.T_REQ_NAMES r
  ON k.NEQ_NORM IS NOT NULL
 AND k.NEQ_NORM = r.REQ_NEQ;




CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME AS
WITH no_neq AS (
  SELECT k.*
  FROM DEV_QUEBECTECH.UTIL.T_COMPANY_KEYS k
  LEFT JOIN DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ m
    ON m.SRC = k.SRC AND m.SRC_ID = k.SRC_ID
  WHERE m.SRC_ID IS NULL
    AND k.NAME_NORM IS NOT NULL
    AND k.P4 IS NOT NULL
    AND k.TOK1 IS NOT NULL
),
cand AS (
  SELECT
    k.SRC, k.SRC_ID,
    r.REQ_NEQ,
    DEV_QUEBECTECH.UTIL.NAME_SIM(k.NAME_NORM, r.REQ_NAME_NORM)::FLOAT AS SCORE
  FROM no_neq k
  JOIN DEV_QUEBECTECH.UTIL.T_REQ_NAMES r
    ON k.P4 = r.REQ_P4
   AND k.TOK1 = r.REQ_TOK1
)
SELECT
  SRC, SRC_ID,
  REQ_NEQ,
  'REQ_NAME_SIM' AS MATCH_TYPE,
  SCORE
FROM cand
WHERE SCORE >= 0.90;




