CREATE OR REPLACE VIEW DEV_QUEBECTECH.UTIL.V_COMPANY_RESOLUTION AS
SELECT
  c.CLUSTER_ID,
  e.SRC,
  e.SRC_ID,
  e.NAME_RAW,
  e.DOMAIN_NORM,
  e.LINKEDIN_NORM,
  e.NEQ_NORM
FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
JOIN DEV_QUEBECTECH.UTIL.T_ENTITIES e
  ON e.SRC = c.SRC AND e.SRC_ID = c.SRC_ID;
