/* ============================================================
   Updated for new pipeline objects:
   - clusters:        DEV_QUEBECTECH.UTIL.T_CLUSTERS
   - HS clean view:   DEV_QUEBECTECH.UTIL.V_HS_CLEAN
   - DRM latest view: DEV_QUEBECTECH.UTIL.V_DRM_LATEST
   - safety gate:     DEV_QUEBECTECH.UTIL.T_CLUSTER_FLAGS (TRANSIENT)

   Changes vs old:
   - only push links for SAFE clusters (FLAG_ANY_CONFLICT = 0)
   - robust HS ID cast with TRY_TO_NUMBER
   - keep requirement: exactly 1 Dealroom company in cluster
   ============================================================ */

CREATE OR REPLACE VIEW DEV_QUEBECTECH.UTIL.V_PUSH_HS_DEALROOM_LINK AS
WITH hc AS (
  SELECT
    c.CLUSTER_ID,
    TRY_TO_NUMBER(c.SRC_ID) AS HS_COMPANY_ID
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
  WHERE c.SRC = 'HUBSPOT'
),
safe AS (
  SELECT CLUSTER_ID
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_FLAGS
  WHERE FLAG_ANY_CONFLICT = 0
),
dr_in_cluster AS (
  SELECT
    c.CLUSTER_ID,
    COUNT(*) AS N_DRM,
    MAX(d.DRM_ID) AS DRM_ID,
    MAX(d.DRM_DEALROOM_URL) AS DRM_URL,
    MAX(d.DRM_WEBSITE_RAW) AS DRM_WEBSITE,
    MAX(d.DRM_LINKEDIN_RAW) AS DRM_LINKEDIN
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
  JOIN DEV_QUEBECTECH.UTIL.V_DRM_LATEST d
    ON d.DRM_ID = c.SRC_ID
  WHERE c.SRC = 'DEALROOM'
  GROUP BY 1
),
hs AS (
  SELECT * FROM DEV_QUEBECTECH.UTIL.V_HS_CLEAN
)
SELECT
  hs.HS_COMPANY_ID,
  hc.CLUSTER_ID,

  IFF(DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_ID_RAW) IS NULL, dr.DRM_ID, NULL)             AS SUGGEST_DRM_ID,
  IFF(DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_URL_RAW) IS NULL, dr.DRM_URL, NULL)           AS SUGGEST_DRM_URL,
  IFF(DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_WEBSITE_RAW) IS NULL, dr.DRM_WEBSITE, NULL)   AS SUGGEST_DRM_WEBSITE,
  IFF(DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_LINKEDIN_RAW) IS NULL, dr.DRM_LINKEDIN, NULL) AS SUGGEST_DRM_LINKEDIN

FROM hc
JOIN safe s
  ON s.CLUSTER_ID = hc.CLUSTER_ID
JOIN hs
  ON hs.HS_COMPANY_ID = hc.HS_COMPANY_ID
JOIN dr_in_cluster dr
  ON dr.CLUSTER_ID = hc.CLUSTER_ID

WHERE
  dr.N_DRM = 1
  AND (
    DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_ID_RAW) IS NULL
    OR DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_URL_RAW) IS NULL
    OR DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_WEBSITE_RAW) IS NULL
    OR DEV_QUEBECTECH.UTIL.NORM_TXT(hs.HS_DEALROOM_LINKEDIN_RAW) IS NULL
  )
;
