USE DATABASE DEV_QUEBECTECH;


CREATE OR REPLACE TABLE REF.INDUSTRY_KEYWORDS (
  INDUSTRY_LABEL STRING,
  KEYWORD        STRING,
  WEIGHT         FLOAT,
  ACTIVE         BOOLEAN,
  NOTES          STRING,
  CREATED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE REF.TECHNOLOGY_KEYWORDS (
  TECHNOLOGY_LABEL STRING,
  KEYWORD          STRING,
  WEIGHT           FLOAT,
  ACTIVE           BOOLEAN,
  NOTES            STRING,
  CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);


COPY INTO REF.TECHNOLOGY_KEYWORDS
  (TECHNOLOGY_LABEL, KEYWORD, WEIGHT, ACTIVE, NOTES)
FROM @DEV_QUEBECTECH.REF.TECH_KEYWORDS/technology_keywords_simplified.csv
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);

COPY INTO REF.INDUSTRY_KEYWORDS
  (INDUSTRY_LABEL, KEYWORD, WEIGHT, ACTIVE, NOTES)
FROM @DEV_QUEBECTECH.REF.INDUSTRY_KEYWORDS/industry_keywords_simplified.csv
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);




CREATE OR REPLACE FUNCTION UTIL.KEYWORD_TO_REGEX(keyword STRING)
RETURNS STRING
LANGUAGE SQL
AS
$$
  -- keyword is plain text; we:
  -- 1) normalize like MATCH_TEXT does
  -- 2) replace spaces with \s+ to be tolerant
  -- 3) wrap with .* ... .* because Snowflake REGEXP_LIKE is implicitly anchored
  CONCAT(
    '.*\\b',
    REGEXP_REPLACE(UTIL.NORMALIZE_TEXT_FOR_MATCHING(keyword), '\\s+', '\\\\s+'),
    '\\b.*'
  )
$$;


CREATE OR REPLACE VIEW REF.INDUSTRY_KEYWORDS_COMPILED AS
SELECT
  INDUSTRY_LABEL,
  KEYWORD,
  WEIGHT,
  ACTIVE,
  NOTES,
  UTIL.KEYWORD_TO_REGEX(KEYWORD) AS KEYWORD_REGEX
FROM REF.INDUSTRY_KEYWORDS
WHERE ACTIVE;

CREATE OR REPLACE VIEW REF.TECHNOLOGY_KEYWORDS_COMPILED AS
SELECT
  TECHNOLOGY_LABEL,
  KEYWORD,
  WEIGHT,
  ACTIVE,
  NOTES,
  UTIL.KEYWORD_TO_REGEX(KEYWORD) AS KEYWORD_REGEX
FROM REF.TECHNOLOGY_KEYWORDS
WHERE ACTIVE;
