CREATE OR REPLACE VIEW DEV_QUEBECTECH.UTIL.V_PUSH_DRM_ENRICH AS
WITH dc AS (
  SELECT
    c.CLUSTER_ID,
    c.SRC_ID AS DRM_ID
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
  WHERE c.SRC = 'DEALROOM'
),
d AS (
  SELECT * FROM DEV_QUEBECTECH.UTIL.V_DRM_LATEST
),
g AS (
  SELECT * FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_GOLDEN
)
SELECT
  d.DRM_ID,
  dc.CLUSTER_ID,

  IFF(d.DRM_NEQ_NORM IS NULL AND g.GOLD_NEQ IS NOT NULL, g.GOLD_NEQ, NULL) AS SUGGEST_NEQ,
  IFF(d.DRM_DOMAIN_NORM IS NULL AND g.GOLD_DOMAIN IS NOT NULL, g.GOLD_DOMAIN, NULL) AS SUGGEST_DOMAIN,
  IFF(d.DRM_LINKEDIN_NORM IS NULL AND g.GOLD_LINKEDIN IS NOT NULL, g.GOLD_LINKEDIN, NULL) AS SUGGEST_LINKEDIN,

  d.DRM_NAME_RAW,
  d.DRM_WEBSITE_RAW,
  d.DRM_LINKEDIN_RAW,
  d.DRM_NEQ_RAW
FROM dc
JOIN d
  ON d.DRM_ID = dc.DRM_ID
JOIN g
  ON g.CLUSTER_ID = dc.CLUSTER_ID
WHERE
  (d.DRM_NEQ_NORM IS NULL AND g.GOLD_NEQ IS NOT NULL)
  OR (d.DRM_DOMAIN_NORM IS NULL AND g.GOLD_DOMAIN IS NOT NULL)
  OR (d.DRM_LINKEDIN_NORM IS NULL AND g.GOLD_LINKEDIN IS NOT NULL);
