USE DATABASE DEV_QUEBECTECH;

WITH active_aab AS (
  SELECT sc.DEALROOM_ID
  FROM SILVER.DRM_STARTUP_CLASSIFICATION_SILVER sc
  JOIN SILVER.DRM_STARTUP_LIFECYCLE_SILVER lc
    ON lc.DEALROOM_ID = sc.DEALROOM_ID
  WHERE lc.LIFECYCLE_BUCKET = 'active_startup'
    AND sc.RATING_LETTER IN ('A+','A','B')
),
base AS (
  SELECT
    c.DEALROOM_ID,
    c.INDUSTRIES_ARR,
    c.SUB_INDUSTRIES_ARR
  FROM SILVER.DRM_COMPANY_SILVER c
  JOIN active_aab a
    ON a.DEALROOM_ID = c.DEALROOM_ID
)
SELECT DISTINCT
  'INDUSTRIES_ARR' AS SOURCE_COL,
  TRIM(f.value::string) AS VALUE
FROM base b,
LATERAL FLATTEN(input => b.INDUSTRIES_ARR) f
WHERE f.value IS NOT NULL
  AND TRIM(f.value::string) <> ''

UNION ALL

SELECT DISTINCT
  'SUB_INDUSTRIES_ARR' AS SOURCE_COL,
  TRIM(f.value::string) AS VALUE
FROM base b,
LATERAL FLATTEN(input => b.SUB_INDUSTRIES_ARR) f
WHERE f.value IS NOT NULL
  AND TRIM(f.value::string) <> ''

ORDER BY 1,2;

