/* ============================================================
   GOLDEN RECORDS — 5-Source Priority
   ============================================================
   Source Priority: REGISTRY > PITCHBOOK > DEALROOM > HARMONIC > HUBSPOT

   Part 1: T_CLUSTER_FLAGS (TRANSIENT) — conflict detection
   Part 2: T_CLUSTER_GOLDEN (TRANSIENT) — golden record per cluster
           Now includes ALL clusters (flagged), not just safe ones.
           Downstream consumers filter on FLAG_ANY_CONFLICT.
   ============================================================ */

USE DATABASE DEV_QUEBECTECH;
USE SCHEMA UTIL;

------------------------------------------------------------
-- 1) CLUSTER FLAGS  (TRANSIENT, NOT TEMP)
------------------------------------------------------------
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_FLAGS AS
WITH
-- All commercial entities within each cluster
e AS (
  SELECT
    c.CLUSTER_ID,
    t.SRC,
    t.SRC_ID,
    t.NAME_NORM,
    t.DOMAIN_NORM,
    t.LINKEDIN_NORM,
    t.NEQ_NORM
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
  JOIN DEV_QUEBECTECH.UTIL.T_ENTITIES t
    ON t.SRC = c.SRC
   AND t.SRC_ID = c.SRC_ID
  WHERE c.SRC <> 'REGISTRY'
),

agg AS (
  SELECT
    CLUSTER_ID,
    COUNT(DISTINCT IFF(NEQ_NORM      IS NOT NULL, NEQ_NORM,      NULL)) AS N_NEQ,
    COUNT(DISTINCT IFF(DOMAIN_NORM   IS NOT NULL, DOMAIN_NORM,   NULL)) AS N_DOMAIN,
    COUNT(DISTINCT IFF(LINKEDIN_NORM IS NOT NULL, LINKEDIN_NORM, NULL)) AS N_LINKEDIN,
    MIN(IFF(NEQ_NORM      IS NOT NULL, NEQ_NORM,      NULL)) AS ANY_NEQ,
    MIN(IFF(DOMAIN_NORM   IS NOT NULL, DOMAIN_NORM,   NULL)) AS ANY_DOMAIN,
    MIN(IFF(LINKEDIN_NORM IS NOT NULL, LINKEDIN_NORM, NULL)) AS ANY_LINKEDIN
  FROM e
  GROUP BY 1
),

name_domain_pairs AS (
  SELECT
    a.CLUSTER_ID,
    MAX(
      IFF(
        a.DOMAIN_NORM IS NOT NULL
        AND a.DOMAIN_NORM = b.DOMAIN_NORM
        AND a.NAME_NORM IS NOT NULL
        AND b.NAME_NORM IS NOT NULL
        AND DEV_QUEBECTECH.UTIL.NAME_SIM(a.NAME_NORM, b.NAME_NORM) < 0.70,
        1, 0
      )
    ) AS HAS_DOMAIN_NAME_MISMATCH
  FROM e a
  JOIN e b
    ON a.CLUSTER_ID = b.CLUSTER_ID
   AND (a.SRC, a.SRC_ID) < (b.SRC, b.SRC_ID)
  GROUP BY 1
),

cluster_has_registry AS (
  SELECT
    CLUSTER_ID,
    MAX(IFF(SRC='REGISTRY', 1, 0)) AS HAS_REGISTRY_NODE
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS
  GROUP BY 1
),

cluster_registry_ambiguous AS (
  SELECT
    c.CLUSTER_ID,
    1 AS HAS_REGISTRY_AMBIGUOUS_LINK
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
  JOIN DEV_QUEBECTECH.UTIL.T_REQ_CLUSTER_CONFLICTS x
    ON x.REQ_NEQ = c.SRC_ID
  WHERE c.SRC = 'REGISTRY'
  GROUP BY 1
)

SELECT
  a.CLUSTER_ID,

  IFF(a.N_NEQ > 1, 1, 0)      AS FLAG_NEQ_CONFLICT,
  IFF(a.N_DOMAIN > 1, 1, 0)   AS FLAG_DOMAIN_CONFLICT,
  IFF(a.N_LINKEDIN > 1, 1, 0) AS FLAG_LINKEDIN_CONFLICT,

  COALESCE(p.HAS_DOMAIN_NAME_MISMATCH, 0) AS FLAG_DOMAIN_NAME_MISMATCH,

  COALESCE(r.HAS_REGISTRY_NODE, 0) AS FLAG_HAS_REGISTRY_NODE,
  COALESCE(ra.HAS_REGISTRY_AMBIGUOUS_LINK, 0) AS FLAG_REGISTRY_AMBIGUOUS_LINK,

  IFF(
       a.N_NEQ > 1
    OR a.N_DOMAIN > 1
    OR a.N_LINKEDIN > 1
    OR COALESCE(p.HAS_DOMAIN_NAME_MISMATCH, 0) = 1
    OR COALESCE(ra.HAS_REGISTRY_AMBIGUOUS_LINK, 0) = 1,
    1, 0
  ) AS FLAG_ANY_CONFLICT,

  a.ANY_NEQ,
  a.ANY_DOMAIN,
  a.ANY_LINKEDIN
FROM agg a
LEFT JOIN name_domain_pairs p
  ON p.CLUSTER_ID = a.CLUSTER_ID
LEFT JOIN cluster_has_registry r
  ON r.CLUSTER_ID = a.CLUSTER_ID
LEFT JOIN cluster_registry_ambiguous ra
  ON ra.CLUSTER_ID = a.CLUSTER_ID
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_FLAGS
  CLUSTER BY (FLAG_ANY_CONFLICT, CLUSTER_ID);

------------------------------------------------------------
-- 2) CLUSTER GOLDEN — ALL clusters (with conflict flags)
--    Priority: REGISTRY > PITCHBOOK > DEALROOM > HARMONIC > HUBSPOT
------------------------------------------------------------
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_GOLDEN AS
WITH
-- Commercial entities in clusters
e_commercial AS (
  SELECT
    c.CLUSTER_ID,
    t.SRC,
    t.SRC_ID,
    t.NAME_RAW,
    t.DOMAIN_NORM,
    t.LINKEDIN_NORM,
    t.NEQ_NORM
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
  JOIN DEV_QUEBECTECH.UTIL.T_ENTITIES t
    ON t.SRC = c.SRC AND t.SRC_ID = c.SRC_ID
  WHERE c.SRC <> 'REGISTRY'
),

-- Registry nodes in clusters
e_registry AS (
  SELECT
    c.CLUSTER_ID,
    c.SRC_ID AS REQ_NEQ
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS c
  WHERE c.SRC = 'REGISTRY'
),

-- Collect fields per cluster with 5-source priority
ranked AS (
  SELECT
    f.CLUSTER_ID,

    -- Registry NEQ (from registry node)
    MAX(er.REQ_NEQ) AS NEQ_FROM_REGISTRY,

    -- NEQ from commercial sources (priority order)
    MAX(IFF(e.SRC='PITCHBOOK', e.NEQ_NORM, NULL)) AS NEQ_FROM_PITCHBOOK,
    MAX(IFF(e.SRC='DEALROOM',  e.NEQ_NORM, NULL)) AS NEQ_FROM_DEALROOM,
    MAX(IFF(e.SRC='HARMONIC',  e.NEQ_NORM, NULL)) AS NEQ_FROM_HARMONIC,
    MAX(IFF(e.SRC='HUBSPOT',   e.NEQ_NORM, NULL)) AS NEQ_FROM_HUBSPOT,

    -- Domain (priority order)
    MAX(IFF(e.SRC='PITCHBOOK', e.DOMAIN_NORM, NULL)) AS DOMAIN_FROM_PITCHBOOK,
    MAX(IFF(e.SRC='DEALROOM',  e.DOMAIN_NORM, NULL)) AS DOMAIN_FROM_DEALROOM,
    MAX(IFF(e.SRC='HARMONIC',  e.DOMAIN_NORM, NULL)) AS DOMAIN_FROM_HARMONIC,
    MAX(IFF(e.SRC='HUBSPOT',   e.DOMAIN_NORM, NULL)) AS DOMAIN_FROM_HUBSPOT,

    -- LinkedIn (priority order)
    MAX(IFF(e.SRC='PITCHBOOK', e.LINKEDIN_NORM, NULL)) AS LINKEDIN_FROM_PITCHBOOK,
    MAX(IFF(e.SRC='DEALROOM',  e.LINKEDIN_NORM, NULL)) AS LINKEDIN_FROM_DEALROOM,
    MAX(IFF(e.SRC='HARMONIC',  e.LINKEDIN_NORM, NULL)) AS LINKEDIN_FROM_HARMONIC,
    MAX(IFF(e.SRC='HUBSPOT',   e.LINKEDIN_NORM, NULL)) AS LINKEDIN_FROM_HUBSPOT,

    -- Name (priority order)
    MAX(r.REQ_NAME_RAW) AS NAME_FROM_REGISTRY,
    MAX(IFF(e.SRC='PITCHBOOK', e.NAME_RAW, NULL)) AS NAME_FROM_PITCHBOOK,
    MAX(IFF(e.SRC='DEALROOM',  e.NAME_RAW, NULL)) AS NAME_FROM_DEALROOM,
    MAX(IFF(e.SRC='HARMONIC',  e.NAME_RAW, NULL)) AS NAME_FROM_HARMONIC,
    MAX(IFF(e.SRC='HUBSPOT',   e.NAME_RAW, NULL)) AS NAME_FROM_HUBSPOT,

    -- Cross-reference IDs (one per source)
    MAX(er.REQ_NEQ)                                AS XREF_REGISTRY_NEQ,
    MAX(IFF(e.SRC='PITCHBOOK', e.SRC_ID, NULL))   AS XREF_PITCHBOOK_ID,
    MAX(IFF(e.SRC='DEALROOM',  e.SRC_ID, NULL))   AS XREF_DEALROOM_ID,
    MAX(IFF(e.SRC='HARMONIC',  e.SRC_ID, NULL))   AS XREF_HARMONIC_ID,
    MAX(IFF(e.SRC='HUBSPOT',   e.SRC_ID, NULL))   AS XREF_HUBSPOT_ID,

    -- Data source tracking
    LISTAGG(DISTINCT e.SRC, ',') WITHIN GROUP (ORDER BY e.SRC) AS COMMERCIAL_SOURCES,
    COUNT(DISTINCT e.SRC) AS COMMERCIAL_SOURCE_COUNT,
    MAX(IFF(er.REQ_NEQ IS NOT NULL, 1, 0)) AS HAS_REGISTRY

  FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_FLAGS f
  LEFT JOIN e_commercial e
    ON e.CLUSTER_ID = f.CLUSTER_ID
  LEFT JOIN e_registry er
    ON er.CLUSTER_ID = f.CLUSTER_ID
  LEFT JOIN DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE r
    ON r.REQ_NEQ = er.REQ_NEQ
  GROUP BY 1
)

SELECT
  CLUSTER_ID,

  -- Core identifiers (priority-resolved)
  COALESCE(NEQ_FROM_REGISTRY, NEQ_FROM_PITCHBOOK, NEQ_FROM_DEALROOM, NEQ_FROM_HARMONIC, NEQ_FROM_HUBSPOT)
    AS GOLD_NEQ,
  COALESCE(DOMAIN_FROM_PITCHBOOK, DOMAIN_FROM_DEALROOM, DOMAIN_FROM_HARMONIC, DOMAIN_FROM_HUBSPOT)
    AS GOLD_DOMAIN,
  COALESCE(LINKEDIN_FROM_PITCHBOOK, LINKEDIN_FROM_DEALROOM, LINKEDIN_FROM_HARMONIC, LINKEDIN_FROM_HUBSPOT)
    AS GOLD_LINKEDIN,
  COALESCE(DOMAIN_FROM_PITCHBOOK, DOMAIN_FROM_DEALROOM, DOMAIN_FROM_HARMONIC, DOMAIN_FROM_HUBSPOT)
    AS GOLD_WEBSITE,
  COALESCE(NAME_FROM_REGISTRY, NAME_FROM_PITCHBOOK, NAME_FROM_DEALROOM, NAME_FROM_HARMONIC, NAME_FROM_HUBSPOT)
    AS GOLD_NAME,

  -- Cross-reference IDs
  XREF_REGISTRY_NEQ   AS GOLD_REGISTRY_NEQ,
  XREF_PITCHBOOK_ID   AS GOLD_PITCHBOOK_ID,
  XREF_DEALROOM_ID    AS GOLD_DEALROOM_ID,
  XREF_HARMONIC_ID    AS GOLD_HARMONIC_ID,
  XREF_HUBSPOT_ID     AS GOLD_HUBSPOT_ID,

  -- Conflict flags (from T_CLUSTER_FLAGS)
  f.FLAG_ANY_CONFLICT,
  f.FLAG_NEQ_CONFLICT,
  f.FLAG_DOMAIN_CONFLICT,
  f.FLAG_LINKEDIN_CONFLICT,

  -- Data source metadata
  IFF(HAS_REGISTRY = 1,
    IFF(COMMERCIAL_SOURCES IS NOT NULL, 'REGISTRY,' || COMMERCIAL_SOURCES, 'REGISTRY'),
    COMMERCIAL_SOURCES
  ) AS DATA_SOURCES,
  COMMERCIAL_SOURCE_COUNT + HAS_REGISTRY AS SOURCE_COUNT

FROM ranked r
JOIN DEV_QUEBECTECH.UTIL.T_CLUSTER_FLAGS f
  ON f.CLUSTER_ID = r.CLUSTER_ID
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_GOLDEN
  CLUSTER BY (GOLD_NEQ, GOLD_DOMAIN, GOLD_LINKEDIN);
