/* ============================================================
   FAST MATCH + CLUSTER PIPELINE (HS 20k, DRM 10k, REQ ~700k)
   Refactor: replace slow recursive clustering with FAST label
   propagation + prune NAME_SIM edges used for clustering.

   Outputs created (same names as before):
   - T_ENTITIES_HS_DRM
   - T_EDGES_HS_DRM
   - T_EDGES_HS_DRM_DEDUP
   - T_CLUSTERS_HS_DRM        <-- refactored (fast)
   - T_CLUSTER_KEYS
   - T_REQ_NAMES_BASE
   - T_REQ_NAMES
   - T_MATCH_REQ_BY_NEQ
   - T_MATCH_REQ_BY_NAME
   - T_REQ_TO_CLUSTER
   - T_REQ_CLUSTER_CONFLICTS
   - T_CLUSTERS
   - T_EDGES_ALL (optional)
   ============================================================ */

USE DATABASE DEV_QUEBECTECH;
USE SCHEMA UTIL;

/* ---------------------------
   1) ENTITIES (HS + DRM only)
   --------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM AS
SELECT
  'HUBSPOT'                                        AS SRC,
  TO_VARCHAR(HS_COMPANY_ID)                        AS SRC_ID,
  HS_NAME_RAW                                      AS NAME_RAW,
  HS_NAME_NORM                                     AS NAME_NORM,
  COALESCE(HS_DOMAIN_NORM, HS_DOMAIN_FROM_WEBSITE) AS DOMAIN_NORM,
  COALESCE(HS_LINKEDIN_ID_NORM, HS_LINKEDIN_NORM)  AS LINKEDIN_NORM,
  HS_NEQ_NORM                                      AS NEQ_NORM,
  SPLIT_PART(HS_NAME_NORM, ' ', 1)                 AS TOK1,
  LEFT(HS_NAME_NORM, 4)                            AS P4
FROM DEV_QUEBECTECH.UTIL.V_HS_CLEAN
WHERE HS_NAME_NORM IS NOT NULL

UNION ALL

SELECT
  'DEALROOM'                                       AS SRC,
  DRM_ID                                           AS SRC_ID,
  DRM_NAME_RAW                                     AS NAME_RAW,
  DRM_NAME_NORM                                    AS NAME_NORM,
  DRM_DOMAIN_NORM                                  AS DOMAIN_NORM,
  DRM_LINKEDIN_NORM                                AS LINKEDIN_NORM,
  DRM_NEQ_NORM                                     AS NEQ_NORM,
  SPLIT_PART(DRM_NAME_NORM, ' ', 1)                AS TOK1,
  LEFT(DRM_NAME_NORM, 4)                           AS P4
FROM DEV_QUEBECTECH.UTIL.V_DRM_LATEST
WHERE DRM_NAME_NORM IS NOT NULL
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM
  CLUSTER BY (SRC, NEQ_NORM, DOMAIN_NORM, LINKEDIN_NORM, P4, TOK1);

/* ---------------------------
   2) EDGES (HS <-> DRM only)
   --------------------------- */

-- Deterministic edges (fast)
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM AS
WITH hs AS (SELECT * FROM DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM WHERE SRC='HUBSPOT'),
     dr AS (SELECT * FROM DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM WHERE SRC='DEALROOM')
SELECT
  'HUBSPOT' AS SRC_A, hs.SRC_ID AS ID_A,
  'DEALROOM' AS SRC_B, dr.SRC_ID AS ID_B,
  'NEQ' AS MATCH_TYPE,
  1.0::FLOAT AS SCORE
FROM hs
JOIN dr
  ON hs.NEQ_NORM IS NOT NULL
 AND hs.NEQ_NORM = dr.NEQ_NORM

UNION ALL
SELECT
  'HUBSPOT', hs.SRC_ID,
  'DEALROOM', dr.SRC_ID,
  'DOMAIN',
  0.95::FLOAT
FROM hs
JOIN dr
  ON hs.DOMAIN_NORM IS NOT NULL
 AND hs.DOMAIN_NORM = dr.DOMAIN_NORM

UNION ALL
SELECT
  'HUBSPOT', hs.SRC_ID,
  'DEALROOM', dr.SRC_ID,
  'LINKEDIN',
  0.95::FLOAT
FROM hs
JOIN dr
  ON hs.LINKEDIN_NORM IS NOT NULL
 AND hs.LINKEDIN_NORM = dr.LINKEDIN_NORM
;

-- Optional fuzzy HS<->DRM ONLY for HS with no deterministic match (blocked + capped)
INSERT INTO DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM
WITH
hs AS (SELECT * FROM DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM WHERE SRC='HUBSPOT'),
dr AS (SELECT * FROM DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM WHERE SRC='DEALROOM'),
hs_det AS (
  SELECT DISTINCT ID_A AS HS_ID
  FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM
  WHERE SRC_A='HUBSPOT'
),
hs_unmatched AS (
  SELECT *
  FROM hs
  WHERE SRC_ID NOT IN (SELECT HS_ID FROM hs_det)
    AND NAME_NORM IS NOT NULL
    AND P4 IS NOT NULL
    AND TOK1 IS NOT NULL
),
cand AS (
  SELECT
    a.SRC_ID AS HS_ID,
    b.SRC_ID AS DRM_ID,
    DEV_QUEBECTECH.UTIL.NAME_SIM(a.NAME_NORM, b.NAME_NORM)::FLOAT AS SCORE
  FROM hs_unmatched a
  JOIN dr b
    ON a.P4  = b.P4
   AND a.TOK1 = b.TOK1
)
SELECT
  'HUBSPOT' AS SRC_A, HS_ID AS ID_A,
  'DEALROOM' AS SRC_B, DRM_ID AS ID_B,
  'NAME_SIM' AS MATCH_TYPE,
  SCORE
FROM cand
WHERE SCORE >= 0.90
QUALIFY ROW_NUMBER() OVER (PARTITION BY HS_ID ORDER BY SCORE DESC) <= 3
;

-- Deduplicate edges (important)
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_DEDUP AS
SELECT DISTINCT SRC_A, ID_A, SRC_B, ID_B, MATCH_TYPE, SCORE
FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_DEDUP
  CLUSTER BY (SRC_A, SRC_B, ID_A, ID_B);

/* ----------------------------------------
   3) CLUSTERS (HS + DRM ONLY)  **FAST VERSION**
   - prune NAME_SIM edges for clustering
   - label propagation (iterative) instead of recursion
   ---------------------------------------- */

-- 3A) Build a lighter edge set just for clustering
CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_CLUSTER AS
WITH det AS (
  SELECT SRC_A, ID_A, SRC_B, ID_B, MATCH_TYPE, SCORE
  FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_DEDUP
  WHERE MATCH_TYPE IN ('NEQ','DOMAIN','LINKEDIN')
),
name_edges AS (
  SELECT SRC_A, ID_A, SRC_B, ID_B, MATCH_TYPE, SCORE
  FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_DEDUP
  WHERE MATCH_TYPE = 'NAME_SIM'
    AND SCORE >= 0.92  -- tighten to 0.93/0.94 if your graph is still dense
),
hs_top AS (
  SELECT *
  FROM name_edges
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SRC_A, ID_A ORDER BY SCORE DESC) = 1
),
drm_top AS (
  SELECT *
  FROM name_edges
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SRC_B, ID_B ORDER BY SCORE DESC) = 1
),
all_edges AS (
  SELECT * FROM det
  UNION ALL SELECT * FROM hs_top
  UNION ALL SELECT * FROM drm_top
)
SELECT DISTINCT
  SRC_A, ID_A, SRC_B, ID_B
FROM all_edges
;

-- 3B) Undirected adjacency list
CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_UNDIRECTED_HS_DRM AS
SELECT SRC_A AS SRC1, ID_A AS ID1, SRC_B AS SRC2, ID_B AS ID2
FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_CLUSTER
UNION ALL
SELECT SRC_B, ID_B, SRC_A, ID_A
FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_CLUSTER
;

-- 3C) Label propagation loop (Snowflake Scripting)
DECLARE
  v_changes NUMBER := 1;
  v_iter    NUMBER := 0;
BEGIN

  CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM AS
  SELECT DISTINCT
    SRC,
    SRC_ID,
    (SRC || ':' || SRC_ID) AS LABEL
  FROM DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM
  ;

  WHILE (v_changes > 0 AND v_iter < 50) DO
    v_iter := v_iter + 1;

    CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM_NEW AS
    WITH nbr_min AS (
      SELECT
        u.SRC1 AS SRC,
        u.ID1  AS SRC_ID,
        MIN(l2.LABEL) AS MIN_NBR_LABEL
      FROM DEV_QUEBECTECH.UTIL.T_UNDIRECTED_HS_DRM u
      JOIN DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM l2
        ON l2.SRC = u.SRC2 AND l2.SRC_ID = u.ID2
      GROUP BY 1,2
    )
    SELECT
      l.SRC,
      l.SRC_ID,
      LEAST(l.LABEL, COALESCE(n.MIN_NBR_LABEL, l.LABEL)) AS LABEL
    FROM DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM l
    LEFT JOIN nbr_min n
      ON n.SRC = l.SRC AND n.SRC_ID = l.SRC_ID
    ;

    SELECT COUNT(*)
      INTO :v_changes
    FROM DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM_NEW n
    JOIN DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM o
      ON o.SRC = n.SRC AND o.SRC_ID = n.SRC_ID
    WHERE n.LABEL <> o.LABEL
    ;

    ALTER TABLE DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM
      SWAP WITH DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM_NEW
    ;

  END WHILE;

  CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTERS_HS_DRM AS
  SELECT
    SRC,
    SRC_ID,
    LABEL AS CLUSTER_ID
  FROM DEV_QUEBECTECH.UTIL.T_LABELS_HS_DRM
  ;

END;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_CLUSTERS_HS_DRM
  CLUSTER BY (CLUSTER_ID, SRC);

/* ------------------------------------------------------
   4) BUILD CLUSTER-LEVEL KEYS (reduces REQ matching work)
   ------------------------------------------------------ */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS AS
WITH e AS (
  SELECT
    c.CLUSTER_ID,
    t.*
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS_HS_DRM c
  JOIN DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM t
    ON t.SRC = c.SRC AND t.SRC_ID = c.SRC_ID
),
agg AS (
  SELECT
    CLUSTER_ID,
    COALESCE(MAX(IFF(SRC='DEALROOM', NEQ_NORM, NULL)), MAX(IFF(SRC='HUBSPOT', NEQ_NORM, NULL))) AS CL_NEQ,
    COALESCE(MAX(IFF(SRC='DEALROOM', DOMAIN_NORM, NULL)), MAX(IFF(SRC='HUBSPOT', DOMAIN_NORM, NULL))) AS CL_DOMAIN,
    COALESCE(MAX(IFF(SRC='DEALROOM', LINKEDIN_NORM, NULL)), MAX(IFF(SRC='HUBSPOT', LINKEDIN_NORM, NULL))) AS CL_LINKEDIN,
    COALESCE(MAX(IFF(SRC='DEALROOM', NAME_NORM, NULL)), MAX(IFF(SRC='HUBSPOT', NAME_NORM, NULL))) AS CL_NAME_NORM
  FROM e
  GROUP BY 1
)
SELECT
  CLUSTER_ID,
  CL_NEQ       AS NEQ_NORM,
  CL_DOMAIN    AS DOMAIN_NORM,
  CL_LINKEDIN  AS LINKEDIN_NORM,
  CL_NAME_NORM AS NAME_NORM,
  SPLIT_PART(CL_NAME_NORM, ' ', 1) AS TOK1,
  LEFT(CL_NAME_NORM, 4)            AS P4
FROM agg
WHERE NAME_NORM IS NOT NULL
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS
  CLUSTER BY (NEQ_NORM, P4, TOK1);

/* ---------------------------------------------------------
   5) REQ NAME TABLE (one row per NEQ, normalized + blocked)
   (Kept as your version; consider refreshing this separately
    if it’s still a bottleneck in your environment.)
   --------------------------------------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE AS
WITH n AS (
  SELECT
    NEQ,
    NOM_ASSUJ,
    DAT_INIT_NOM_ASSUJ,
    DAT_FIN_NOM_ASSUJ,
    ROW_NUMBER() OVER (
      PARTITION BY DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ)
      ORDER BY IFF(DAT_FIN_NOM_ASSUJ IS NULL, 0, 1), DAT_INIT_NOM_ASSUJ DESC
    ) AS RN
  FROM DEV_DATAMART.ENTREPRISES_DU_QUEBEC.REGISTRE_NOMS
  -- If REGISTRE_NOMS contains history, this single line usually cuts runtime massively:
  -- WHERE DAT_FIN_NOM_ASSUJ IS NULL
)
SELECT
  DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ)        AS REQ_NEQ,
  NOM_ASSUJ                                AS REQ_NAME_RAW,
  DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ) AS REQ_NAME_NORM,
  SPLIT_PART(DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ), ' ', 1) AS REQ_TOK1,
  LEFT(DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ), 4)            AS REQ_P4
FROM n
WHERE RN = 1
  AND DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ) IS NOT NULL
  AND DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ) IS NOT NULL
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE
  CLUSTER BY (REQ_P4, REQ_TOK1, REQ_NEQ);

-- Filter REQ rows to only prefixes we actually need
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES AS
WITH p AS (
  SELECT DISTINCT P4
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS
  WHERE P4 IS NOT NULL
)
SELECT r.*
FROM DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE r
JOIN p
  ON p.P4 = r.REQ_P4
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES
  CLUSTER BY (REQ_P4, REQ_TOK1, REQ_NEQ);

/* -------------------------------------------
   6) MATCH CLUSTERS -> REQ (NEQ first, then name)
   ------------------------------------------- */

-- 6A) Exact NEQ match
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ AS
SELECT
  k.CLUSTER_ID,
  r.REQ_NEQ,
  'REQ_NEQ' AS MATCH_TYPE,
  1.0::FLOAT AS SCORE
FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS k
JOIN DEV_QUEBECTECH.UTIL.T_REQ_NAMES r
  ON k.NEQ_NORM IS NOT NULL
 AND k.NEQ_NORM = r.REQ_NEQ
;

-- 6B) Name-sim match only for clusters without NEQ match + blocked + capped top 3
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME AS
WITH no_neq AS (
  SELECT k.*
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS k
  LEFT JOIN DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ m
    ON m.CLUSTER_ID = k.CLUSTER_ID
  WHERE m.CLUSTER_ID IS NULL
    AND k.NAME_NORM IS NOT NULL
    AND k.P4 IS NOT NULL
    AND k.TOK1 IS NOT NULL
),
cand AS (
  SELECT
    k.CLUSTER_ID,
    r.REQ_NEQ,
    DEV_QUEBECTECH.UTIL.NAME_SIM(k.NAME_NORM, r.REQ_NAME_NORM)::FLOAT AS SCORE
  FROM no_neq k
  JOIN DEV_QUEBECTECH.UTIL.T_REQ_NAMES r
    ON k.P4   = r.REQ_P4
   AND k.TOK1 = r.REQ_TOK1
),
ranked AS (
  SELECT *
  FROM cand
  WHERE SCORE >= 0.90
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CLUSTER_ID ORDER BY SCORE DESC) <= 3
)
SELECT
  CLUSTER_ID,
  REQ_NEQ,
  'REQ_NAME_SIM' AS MATCH_TYPE,
  SCORE
FROM ranked
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
  CLUSTER BY (REQ_NEQ, CLUSTER_ID);

/* ---------------------------------------------------
   7) ATTACH REQ NEQs TO HS/DRM CLUSTERS (no recursion)
   --------------------------------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_TO_CLUSTER AS
WITH links AS (
  SELECT CLUSTER_ID, REQ_NEQ FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ
  UNION ALL
  SELECT CLUSTER_ID, REQ_NEQ FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
)
SELECT
  REQ_NEQ,
  MIN(CLUSTER_ID) AS CLUSTER_ID,
  COUNT(DISTINCT CLUSTER_ID) AS N_CLUSTERS
FROM links
GROUP BY 1
;

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_CLUSTER_CONFLICTS AS
SELECT *
FROM DEV_QUEBECTECH.UTIL.T_REQ_TO_CLUSTER
WHERE N_CLUSTERS > 1
;

/* ---------------------------
   8) FINAL CLUSTERS TABLE
   --------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTERS AS
SELECT
  SRC,
  SRC_ID,
  CLUSTER_ID
FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS_HS_DRM

UNION ALL

SELECT
  'REGISTRY' AS SRC,
  REQ_NEQ    AS SRC_ID,
  CLUSTER_ID
FROM DEV_QUEBECTECH.UTIL.T_REQ_TO_CLUSTER
WHERE N_CLUSTERS = 1
;

/* ---------------------------
   9) OPTIONAL: EDGES_ALL
   --------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_EDGES_ALL AS
SELECT DISTINCT SRC_A, ID_A, SRC_B, ID_B, MATCH_TYPE, SCORE
FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_DEDUP

UNION

SELECT DISTINCT
  'CLUSTER'  AS SRC_A,
  CLUSTER_ID AS ID_A,
  'REGISTRY' AS SRC_B,
  REQ_NEQ    AS ID_B,
  MATCH_TYPE,
  SCORE
FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ

UNION

SELECT DISTINCT
  'CLUSTER'  AS SRC_A,
  CLUSTER_ID AS ID_A,
  'REGISTRY' AS SRC_B,
  REQ_NEQ    AS ID_B,
  MATCH_TYPE,
  SCORE
FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
;

/* ---------------------------
   10) QUICK HEALTH CHECKS
   --------------------------- */

SELECT 'ENTITIES_HS_DRM' AS OBJ, COUNT(*) N FROM DEV_QUEBECTECH.UTIL.T_ENTITIES_HS_DRM
UNION ALL SELECT 'EDGES_HS_DRM_DEDUP', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_DEDUP
UNION ALL SELECT 'EDGES_HS_DRM_CLUSTER', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_EDGES_HS_DRM_CLUSTER
UNION ALL SELECT 'CLUSTERS_HS_DRM', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS_HS_DRM
UNION ALL SELECT 'CLUSTER_KEYS', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS
UNION ALL SELECT 'REQ_NAMES_BASE', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE
UNION ALL SELECT 'REQ_NAMES_FILTERED', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_REQ_NAMES
UNION ALL SELECT 'REQ_MATCH_NEQ', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ
UNION ALL SELECT 'REQ_MATCH_NAME', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
UNION ALL SELECT 'REQ_CONFLICTS', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_REQ_CLUSTER_CONFLICTS
UNION ALL SELECT 'FINAL_CLUSTERS', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS
;

SELECT
  APPROX_PERCENTILE(N, 0.50) AS P50,
  APPROX_PERCENTILE(N, 0.90) AS P90,
  APPROX_PERCENTILE(N, 0.99) AS P99,
  MAX(N) AS MAX_N
FROM (
  SELECT CLUSTER_ID, COUNT(*) AS N
  FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
  GROUP BY 1
);
