/* ============================================================
   FAST MATCH + CLUSTER PIPELINE — 5-Source Version
   ============================================================
   Reads from:
     T_ENTITIES          (all 5 sources, built by 62_)
     T_EDGES_ALL_DEDUP   (all cross-source edges, built by 63A/63B)

   Produces:
     T_CLUSTERS_COMMERCIAL  — commercial-source clusters via label propagation
     T_CLUSTER_KEYS         — cluster-level aggregated attributes
     T_REQ_NAMES_BASE       — registry names (current only)
     T_MATCH_REQ_BY_NEQ     — exact NEQ matches cluster→registry
     T_MATCH_REQ_BY_NAME    — fuzzy name matches cluster→registry
     T_CLUSTERS             — final clusters (commercial + registry nodes)

   Architecture: same label-propagation approach, but now
   clusters all commercial sources (HS, DRM, PB, HAR) together
   and then attaches Registry nodes via NEQ/name matching.
   ============================================================ */

USE DATABASE DEV_QUEBECTECH;
USE SCHEMA UTIL;

/* ---------------------------
   1) EDGE SUBSET FOR CLUSTERING
   Deterministic + pruned NAME_SIM
   --------------------------- */

CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_EDGES_CLUSTER AS
WITH det AS (
  SELECT SRC_A, ID_A, SRC_B, ID_B, MATCH_TYPE, SCORE
  FROM DEV_QUEBECTECH.UTIL.T_EDGES_ALL_DEDUP
  WHERE MATCH_TYPE IN ('NEQ','DOMAIN','LINKEDIN')
),
name_edges AS (
  SELECT SRC_A, ID_A, SRC_B, ID_B, MATCH_TYPE, SCORE
  FROM DEV_QUEBECTECH.UTIL.T_EDGES_ALL_DEDUP
  WHERE MATCH_TYPE = 'NAME_SIM'
    AND SCORE >= 0.92
),
-- keep top-1 NAME_SIM per each endpoint
a_top AS (
  SELECT *
  FROM name_edges
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SRC_A, ID_A ORDER BY SCORE DESC) = 1
),
b_top AS (
  SELECT *
  FROM name_edges
  QUALIFY ROW_NUMBER() OVER (PARTITION BY SRC_B, ID_B ORDER BY SCORE DESC) = 1
),
all_edges AS (
  SELECT * FROM det
  UNION ALL SELECT * FROM a_top
  UNION ALL SELECT * FROM b_top
)
SELECT DISTINCT SRC_A, ID_A, SRC_B, ID_B
FROM all_edges
;

/* ---------------------------
   2) UNDIRECTED ADJACENCY LIST
   --------------------------- */

CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_UNDIRECTED AS
SELECT SRC_A AS SRC1, ID_A AS ID1, SRC_B AS SRC2, ID_B AS ID2
FROM DEV_QUEBECTECH.UTIL.T_EDGES_CLUSTER
UNION ALL
SELECT SRC_B, ID_B, SRC_A, ID_A
FROM DEV_QUEBECTECH.UTIL.T_EDGES_CLUSTER
;

/* ---------------------------
   3) LABEL PROPAGATION (commercial sources only — excludes REGISTRY)
   --------------------------- */

DECLARE
  v_changes NUMBER := 1;
  v_iter    NUMBER := 0;
BEGIN

  -- Initialize labels for all commercial entities (non-REGISTRY)
  CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_LABELS AS
  SELECT DISTINCT
    SRC,
    SRC_ID,
    (SRC || ':' || SRC_ID) AS LABEL
  FROM DEV_QUEBECTECH.UTIL.T_ENTITIES
  WHERE SRC <> 'REGISTRY'
  ;

  WHILE (v_changes > 0 AND v_iter < 50) DO
    v_iter := v_iter + 1;

    CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_LABELS_NEW AS
    WITH nbr_min AS (
      SELECT
        u.SRC1 AS SRC,
        u.ID1  AS SRC_ID,
        MIN(l2.LABEL) AS MIN_NBR_LABEL
      FROM DEV_QUEBECTECH.UTIL.T_UNDIRECTED u
      JOIN DEV_QUEBECTECH.UTIL.T_LABELS l2
        ON l2.SRC = u.SRC2 AND l2.SRC_ID = u.ID2
      GROUP BY 1,2
    )
    SELECT
      l.SRC,
      l.SRC_ID,
      LEAST(l.LABEL, COALESCE(n.MIN_NBR_LABEL, l.LABEL)) AS LABEL
    FROM DEV_QUEBECTECH.UTIL.T_LABELS l
    LEFT JOIN nbr_min n
      ON n.SRC = l.SRC AND n.SRC_ID = l.SRC_ID
    ;

    SELECT COUNT(*)
      INTO :v_changes
    FROM DEV_QUEBECTECH.UTIL.T_LABELS_NEW n
    JOIN DEV_QUEBECTECH.UTIL.T_LABELS o
      ON o.SRC = n.SRC AND o.SRC_ID = n.SRC_ID
    WHERE n.LABEL <> o.LABEL
    ;

    ALTER TABLE DEV_QUEBECTECH.UTIL.T_LABELS
      SWAP WITH DEV_QUEBECTECH.UTIL.T_LABELS_NEW
    ;

  END WHILE;

  CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTERS_COMMERCIAL AS
  SELECT SRC, SRC_ID, LABEL AS CLUSTER_ID
  FROM DEV_QUEBECTECH.UTIL.T_LABELS
  ;

END;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_CLUSTERS_COMMERCIAL
  CLUSTER BY (CLUSTER_ID, SRC);

/* ------------------------------------------------------
   4) BUILD CLUSTER-LEVEL KEYS
   5-source priority: REGISTRY > PITCHBOOK > DEALROOM > HARMONIC > HUBSPOT
   ------------------------------------------------------ */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS AS
WITH e AS (
  SELECT
    c.CLUSTER_ID,
    t.*
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS_COMMERCIAL c
  JOIN DEV_QUEBECTECH.UTIL.T_ENTITIES t
    ON t.SRC = c.SRC AND t.SRC_ID = c.SRC_ID
),
agg AS (
  SELECT
    CLUSTER_ID,
    COALESCE(
      MAX(IFF(SRC='PITCHBOOK', NEQ_NORM, NULL)),
      MAX(IFF(SRC='DEALROOM',  NEQ_NORM, NULL)),
      MAX(IFF(SRC='HARMONIC',  NEQ_NORM, NULL)),
      MAX(IFF(SRC='HUBSPOT',   NEQ_NORM, NULL))
    ) AS CL_NEQ,
    COALESCE(
      MAX(IFF(SRC='PITCHBOOK', DOMAIN_NORM, NULL)),
      MAX(IFF(SRC='DEALROOM',  DOMAIN_NORM, NULL)),
      MAX(IFF(SRC='HARMONIC',  DOMAIN_NORM, NULL)),
      MAX(IFF(SRC='HUBSPOT',   DOMAIN_NORM, NULL))
    ) AS CL_DOMAIN,
    COALESCE(
      MAX(IFF(SRC='PITCHBOOK', LINKEDIN_NORM, NULL)),
      MAX(IFF(SRC='DEALROOM',  LINKEDIN_NORM, NULL)),
      MAX(IFF(SRC='HARMONIC',  LINKEDIN_NORM, NULL)),
      MAX(IFF(SRC='HUBSPOT',   LINKEDIN_NORM, NULL))
    ) AS CL_LINKEDIN,
    COALESCE(
      MAX(IFF(SRC='PITCHBOOK', NAME_NORM, NULL)),
      MAX(IFF(SRC='DEALROOM',  NAME_NORM, NULL)),
      MAX(IFF(SRC='HARMONIC',  NAME_NORM, NULL)),
      MAX(IFF(SRC='HUBSPOT',   NAME_NORM, NULL))
    ) AS CL_NAME_NORM
  FROM e
  GROUP BY 1
)
SELECT
  CLUSTER_ID,
  CL_NEQ       AS NEQ_NORM,
  CL_DOMAIN    AS DOMAIN_NORM,
  CL_LINKEDIN  AS LINKEDIN_NORM,
  CL_NAME_NORM AS NAME_NORM,
  SPLIT_PART(CL_NAME_NORM, ' ', 1) AS TOK1,
  LEFT(CL_NAME_NORM, 4)            AS P4
FROM agg
WHERE NAME_NORM IS NOT NULL
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS
  CLUSTER BY (NEQ_NORM, P4, TOK1);

/* ---------------------------------------------------------
   5) REQ NAME TABLES (FAST)
   - Build BASE from CURRENT names only (DAT_FIN_NOM_ASSUJ IS NULL)
   - Filter REQ using (P4, TOK1) keys
   - Exclude stopword blocks
   --------------------------------------------------------- */

-- Stopwords (reuse if already created by 63B, otherwise create)
CREATE TEMP TABLE IF NOT EXISTS DEV_QUEBECTECH.UTIL.T_STOPWORDS (W STRING);
DELETE FROM DEV_QUEBECTECH.UTIL.T_STOPWORDS;
INSERT INTO DEV_QUEBECTECH.UTIL.T_STOPWORDS (W) VALUES
  ('the'),('les'),('la'),('le'),('de'),('des'),('du'),
  ('services'),('service'),('solutions'),('solution'),
  ('groupe'),('group'),('technologies'),('technology'),
  ('inc'),('corp'),('company');

-- BASE: one row per NEQ using only CURRENT name rows
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE AS
WITH n AS (
  SELECT
    NEQ,
    NOM_ASSUJ,
    DAT_INIT_NOM_ASSUJ,
    ROW_NUMBER() OVER (
      PARTITION BY DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ)
      ORDER BY DAT_INIT_NOM_ASSUJ DESC
    ) AS RN
  FROM DEV_DATAMART.ENTREPRISES_DU_QUEBEC.REGISTRE_NOMS
  WHERE DAT_FIN_NOM_ASSUJ IS NULL
)
SELECT
  DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ)        AS REQ_NEQ,
  NOM_ASSUJ                                AS REQ_NAME_RAW,
  DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ) AS REQ_NAME_NORM,
  SPLIT_PART(DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ), ' ', 1) AS REQ_TOK1,
  LEFT(DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ), 4)            AS REQ_P4
FROM n
WHERE RN = 1
  AND DEV_QUEBECTECH.UTIL.NORM_NEQ(NEQ) IS NOT NULL
  AND DEV_QUEBECTECH.UTIL.NORM_NAME(NOM_ASSUJ) IS NOT NULL
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE
  CLUSTER BY (REQ_P4, REQ_TOK1, REQ_NEQ);

-- Block keys from clusters: (P4, TOK1), excluding stopwords
CREATE OR REPLACE TEMP TABLE DEV_QUEBECTECH.UTIL.T_REQ_BLOCK_KEYS AS
SELECT DISTINCT
  P4,
  TOK1
FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS
WHERE P4 IS NOT NULL
  AND TOK1 IS NOT NULL
  AND LENGTH(TOK1) >= 3
  AND TOK1 NOT IN (SELECT W FROM DEV_QUEBECTECH.UTIL.T_STOPWORDS)
;

-- FILTERED REQ: only rows in blocks that actually appear in cluster keys
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES AS
SELECT
  b.REQ_NEQ,
  b.REQ_NAME_RAW,
  b.REQ_NAME_NORM,
  b.REQ_TOK1,
  b.REQ_P4
FROM DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE b
JOIN DEV_QUEBECTECH.UTIL.T_REQ_BLOCK_KEYS k
  ON k.P4   = b.REQ_P4
 AND k.TOK1 = b.REQ_TOK1
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_REQ_NAMES
  CLUSTER BY (REQ_P4, REQ_TOK1, REQ_NEQ);

/* -------------------------------------------
   6) MATCH CLUSTERS -> REQ (NEQ first, then name)
   ------------------------------------------- */

-- Exact NEQ match
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ AS
SELECT
  k.CLUSTER_ID,
  r.REQ_NEQ,
  'REQ_NEQ' AS MATCH_TYPE,
  1.0::FLOAT AS SCORE
FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS k
JOIN DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE r
  ON k.NEQ_NORM IS NOT NULL
 AND k.NEQ_NORM = r.REQ_NEQ
;

-- Name match only for clusters without NEQ match + blocked + capped top 3
CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME AS
WITH no_neq AS (
  SELECT k.*
  FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS k
  LEFT JOIN DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ m
    ON m.CLUSTER_ID = k.CLUSTER_ID
  WHERE m.CLUSTER_ID IS NULL
    AND k.NAME_NORM IS NOT NULL
    AND k.P4 IS NOT NULL
    AND k.TOK1 IS NOT NULL
    AND LENGTH(k.TOK1) >= 3
    AND k.TOK1 NOT IN (SELECT W FROM DEV_QUEBECTECH.UTIL.T_STOPWORDS)
),
cand AS (
  SELECT
    k.CLUSTER_ID,
    r.REQ_NEQ,
    DEV_QUEBECTECH.UTIL.NAME_SIM(k.NAME_NORM, r.REQ_NAME_NORM)::FLOAT AS SCORE
  FROM no_neq k
  JOIN DEV_QUEBECTECH.UTIL.T_REQ_NAMES r
    ON k.P4   = r.REQ_P4
   AND k.TOK1 = r.REQ_TOK1
),
ranked AS (
  SELECT *
  FROM cand
  WHERE SCORE >= 0.90
  QUALIFY ROW_NUMBER() OVER (PARTITION BY CLUSTER_ID ORDER BY SCORE DESC) <= 3
)
SELECT
  CLUSTER_ID,
  REQ_NEQ,
  'REQ_NAME_SIM' AS MATCH_TYPE,
  SCORE
FROM ranked
;

ALTER TABLE DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
  CLUSTER BY (REQ_NEQ, CLUSTER_ID);

/* ---------------------------------------------------
   7) ATTACH REQ NEQs TO COMMERCIAL CLUSTERS
   --------------------------------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_TO_CLUSTER AS
WITH links AS (
  SELECT CLUSTER_ID, REQ_NEQ FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ
  UNION ALL
  SELECT CLUSTER_ID, REQ_NEQ FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
)
SELECT
  REQ_NEQ,
  MIN(CLUSTER_ID) AS CLUSTER_ID,
  COUNT(DISTINCT CLUSTER_ID) AS N_CLUSTERS
FROM links
GROUP BY 1
;

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_REQ_CLUSTER_CONFLICTS AS
SELECT *
FROM DEV_QUEBECTECH.UTIL.T_REQ_TO_CLUSTER
WHERE N_CLUSTERS > 1
;

/* ---------------------------
   8) FINAL CLUSTERS TABLE
   --------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_CLUSTERS AS
SELECT
  SRC,
  SRC_ID,
  CLUSTER_ID
FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS_COMMERCIAL

UNION ALL

SELECT
  'REGISTRY' AS SRC,
  REQ_NEQ    AS SRC_ID,
  CLUSTER_ID
FROM DEV_QUEBECTECH.UTIL.T_REQ_TO_CLUSTER
WHERE N_CLUSTERS = 1
;

/* ---------------------------
   9) EDGES_ALL (full audit trail)
   --------------------------- */

CREATE OR REPLACE TRANSIENT TABLE DEV_QUEBECTECH.UTIL.T_EDGES_ALL AS
SELECT DISTINCT SRC_A, ID_A, SRC_B, ID_B, MATCH_TYPE, SCORE
FROM DEV_QUEBECTECH.UTIL.T_EDGES_ALL_DEDUP

UNION

SELECT DISTINCT
  'CLUSTER'  AS SRC_A,
  CLUSTER_ID AS ID_A,
  'REGISTRY' AS SRC_B,
  REQ_NEQ    AS ID_B,
  MATCH_TYPE,
  SCORE
FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ

UNION

SELECT DISTINCT
  'CLUSTER'  AS SRC_A,
  CLUSTER_ID AS ID_A,
  'REGISTRY' AS SRC_B,
  REQ_NEQ    AS ID_B,
  MATCH_TYPE,
  SCORE
FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
;

/* ---------------------------
   10) BACKWARD-COMPAT ALIASES
   --------------------------- */

CREATE OR REPLACE VIEW DEV_QUEBECTECH.UTIL.T_CLUSTERS_HS_DRM AS
SELECT * FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS_COMMERCIAL
WHERE SRC IN ('HUBSPOT','DEALROOM');

CREATE OR REPLACE VIEW DEV_QUEBECTECH.UTIL.T_UNDIRECTED_HS_DRM AS
SELECT * FROM DEV_QUEBECTECH.UTIL.T_UNDIRECTED;

/* ---------------------------
   11) HEALTH CHECKS
   --------------------------- */

SELECT 'ENTITIES' AS OBJ, COUNT(*) N FROM DEV_QUEBECTECH.UTIL.T_ENTITIES
UNION ALL SELECT 'EDGES_ALL_DEDUP', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_EDGES_ALL_DEDUP
UNION ALL SELECT 'EDGES_CLUSTER', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_EDGES_CLUSTER
UNION ALL SELECT 'CLUSTERS_COMMERCIAL', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS_COMMERCIAL
UNION ALL SELECT 'CLUSTER_KEYS', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_CLUSTER_KEYS
UNION ALL SELECT 'REQ_NAMES_BASE', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_REQ_NAMES_BASE
UNION ALL SELECT 'REQ_NAMES_FILTERED', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_REQ_NAMES
UNION ALL SELECT 'REQ_MATCH_NEQ', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NEQ
UNION ALL SELECT 'REQ_MATCH_NAME', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
UNION ALL SELECT 'REQ_CONFLICTS', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_REQ_CLUSTER_CONFLICTS
UNION ALL SELECT 'FINAL_CLUSTERS', COUNT(*) FROM DEV_QUEBECTECH.UTIL.T_CLUSTERS
;

-- Cluster size distribution for REQ name matches
SELECT
  APPROX_PERCENTILE(N, 0.50) AS P50,
  APPROX_PERCENTILE(N, 0.90) AS P90,
  APPROX_PERCENTILE(N, 0.99) AS P99,
  MAX(N) AS MAX_N
FROM (
  SELECT CLUSTER_ID, COUNT(*) AS N
  FROM DEV_QUEBECTECH.UTIL.T_MATCH_REQ_BY_NAME
  GROUP BY 1
);

-- Entity count by source
SELECT SRC, COUNT(*) AS N
FROM DEV_QUEBECTECH.UTIL.T_ENTITIES
GROUP BY 1
ORDER BY 2 DESC;
