-- =============================================================================
-- 07_SILVER_COMPANY_ENRICHED_VIEW.sql
-- =============================================================================
USE DATABASE DEV_QUEBECTECH;


CREATE OR REPLACE VIEW SILVER.DRM_COMPANY_ENRICHED_SILVER AS
SELECT
  c.*,

  g.AGGLOMERATION,
  g.AGGLOMERATION_DETAILS,
  g.MRC,
  g.REGION_ADMIN,
  g.GEO_MATCH_STATUS,
  g.GEO_LABELED_AT,

  i.INDUSTRY_LABELS,
  i.TOP_INDUSTRY,
  i.TOP_INDUSTRY_SCORE,
  i.INDUSTRY_MATCHES,
  i.INDUSTRY_LABELED_AT,

  t.TECHNOLOGY_LABELS,
  t.TOP_TECHNOLOGY,
  t.TOP_TECHNOLOGY_SCORE,
  t.TECHNOLOGY_MATCHES,
  t.TECHNOLOGY_LABELED_AT

FROM SILVER.DRM_COMPANY_SILVER c
LEFT JOIN SILVER.DRM_GEO_ENRICHMENT_SILVER g
  ON c.DEALROOM_ID = g.DEALROOM_ID
LEFT JOIN SILVER.DRM_INDUSTRY_SIGNALS_SILVER i
  ON c.DEALROOM_ID = i.DEALROOM_ID
LEFT JOIN SILVER.DRM_TECHNOLOGY_SIGNALS_SILVER t
  ON c.DEALROOM_ID = t.DEALROOM_ID;




-- =============================================================================
-- 08_SMOKE_TESTS.sql
-- =============================================================================

-- Row counts should match your ~11,136 companies
SELECT COUNT(*) AS n_company FROM SILVER.DRM_COMPANY_SILVER;
SELECT COUNT(*) AS n_geo     FROM SILVER.DRM_GEO_ENRICHMENT_SILVER;
SELECT COUNT(*) AS n_ind     FROM SILVER.DRM_INDUSTRY_SIGNALS_SILVER;
SELECT COUNT(*) AS n_tech    FROM SILVER.DRM_TECHNOLOGY_SIGNALS_SILVER;

-- Geo match rate
SELECT
  GEO_MATCH_STATUS,
  COUNT(*) AS n
FROM SILVER.DRM_GEO_ENRICHMENT_SILVER
GROUP BY 1
ORDER BY 2 DESC;

-- % of companies with at least one industry label
SELECT
  COUNT_IF(INDUSTRY_LABELS IS NOT NULL) / NULLIF(COUNT(*),0) AS pct_with_industry
FROM SILVER.DRM_COMPANY_ENRICHED_SILVER;

-- % of companies with at least one technology label
SELECT
  COUNT_IF(TECHNOLOGY_LABELS IS NOT NULL) / NULLIF(COUNT(*),0) AS pct_with_technology
FROM SILVER.DRM_COMPANY_ENRICHED_SILVER;

-- Quick sample of unmapped HQ cities (review candidates)
SELECT HQ_CITY, HQ_CITY_KEY
FROM SILVER.DRM_GEO_ENRICHMENT_SILVER
WHERE GEO_MATCH_STATUS = 'unmatched'
QUALIFY ROW_NUMBER() OVER (ORDER BY HQ_CITY) <= 50;


SELECT COUNT(*) FROM SILVER.DRM_COMPANY_SILVER;
SELECT COUNT(*) FROM SILVER.DRM_INDUSTRY_SIGNALS_SILVER;
SELECT COUNT(*) FROM SILVER.DRM_TECHNOLOGY_SIGNALS_SILVER;

SELECT COUNT_IF(INDUSTRY_LABELS IS NOT NULL) AS N_WITH_INDUSTRY
FROM SILVER.DRM_INDUSTRY_SIGNALS_SILVER;

SELECT COUNT_IF(TECHNOLOGY_LABELS IS NOT NULL) AS N_WITH_TECH
FROM SILVER.DRM_TECHNOLOGY_SIGNALS_SILVER;
