USE DATABASE DEV_QUEBECTECH;

CREATE OR REPLACE TEMP TABLE SILVER.STG_MANUAL_STARTUP_REVIEW (
  DEALROOM_URL   STRING,
  STARTUP_STATUS STRING
);

COPY INTO SILVER.STG_MANUAL_STARTUP_REVIEW
FROM '@"DEV_QUEBECTECH"."SILVER"."MANUAL_REVIEWS"/startup_status/manual_reviews_startup_vs_non_startups_10_02_2026.csv'
FILE_FORMAT = (TYPE=CSV FIELD_OPTIONALLY_ENCLOSED_BY='"' SKIP_HEADER=1);


-- Any statuses outside expected values?
SELECT LOWER(TRIM(STARTUP_STATUS)) AS STARTUP_STATUS_NORM, COUNT(*) N
FROM SILVER.STG_MANUAL_STARTUP_REVIEW
GROUP BY 1
ORDER BY 2 DESC;


-- Any URLs that don't match a Dealroom company?
WITH s AS (
  SELECT UTIL.NORMALIZE_DEALROOM_URL(DEALROOM_URL) AS URL_NORM, *
  FROM SILVER.STG_MANUAL_STARTUP_REVIEW
)
SELECT COUNT(*) AS N_UNMATCHED
FROM s
LEFT JOIN SILVER.DRM_COMPANY_URLS_VW c
  ON c.DEALROOM_URL_NORM = s.URL_NORM
WHERE c.DEALROOM_ID IS NULL;


-- Optional: list them for manual fixes:
WITH s AS (
  SELECT UTIL.NORMALIZE_DEALROOM_URL(DEALROOM_URL) AS URL_NORM, *
  FROM SILVER.STG_MANUAL_STARTUP_REVIEW
)
SELECT s.DEALROOM_URL, s.STARTUP_STATUS
FROM s
LEFT JOIN SILVER.DRM_COMPANY_URLS_VW c
  ON c.DEALROOM_URL_NORM = s.URL_NORM
WHERE c.DEALROOM_ID IS NULL
ORDER BY 1;



-- 1) Deactivate previous manual overrides for these companies (latest wins)
UPDATE SILVER.DRM_STARTUP_OVERRIDES o
SET IS_ACTIVE = FALSE
WHERE o.IS_ACTIVE = TRUE
  AND o.SOURCE = 'manual_csv_upload'
  AND o.DEALROOM_ID IN (
    SELECT DISTINCT c.DEALROOM_ID
    FROM SILVER.STG_MANUAL_STARTUP_REVIEW r
    JOIN SILVER.DRM_COMPANY_URLS_VW c
      ON c.DEALROOM_URL_NORM = UTIL.NORMALIZE_DEALROOM_URL(r.DEALROOM_URL)
    WHERE LOWER(TRIM(r.STARTUP_STATUS)) IN ('startup','non-startup','for-review')
  );


-- 2) Insert new overrides (startup / non-startup / for-review)
INSERT INTO SILVER.DRM_STARTUP_OVERRIDES (
  DEALROOM_ID,
  DEALROOM_URL_INPUT,
  DEALROOM_URL_NORM,
  STARTUP_STATUS,
  RATING_LETTER,
  RATING_REASON,
  OVERRIDDEN_BY,
  OVERRIDE_REASON,
  SOURCE,
  OVERRIDDEN_AT,
  IS_ACTIVE
)
SELECT
  c.DEALROOM_ID,
  r.DEALROOM_URL AS DEALROOM_URL_INPUT,
  c.DEALROOM_URL_NORM,
  LOWER(TRIM(r.STARTUP_STATUS)) AS STARTUP_STATUS,

  /* Rating mapping */
  CASE
    WHEN LOWER(TRIM(r.STARTUP_STATUS)) = 'startup'     THEN 'A+'
    WHEN LOWER(TRIM(r.STARTUP_STATUS)) = 'for-review'  THEN 'C'
    WHEN LOWER(TRIM(r.STARTUP_STATUS)) = 'non-startup' THEN 'D'
    ELSE NULL
  END AS RATING_LETTER,

  /* Reason mapping */
  CASE
    WHEN LOWER(TRIM(r.STARTUP_STATUS)) = 'startup'     THEN 'A+_manual_review'
    WHEN LOWER(TRIM(r.STARTUP_STATUS)) = 'for-review'  THEN 'for_review'
    WHEN LOWER(TRIM(r.STARTUP_STATUS)) = 'non-startup' THEN 'manual_review'
    ELSE NULL
  END AS RATING_REASON,

  CURRENT_USER() AS OVERRIDDEN_BY,
  'manual_review_upload' AS OVERRIDE_REASON,
  'manual_csv_upload' AS SOURCE,
  CURRENT_TIMESTAMP() AS OVERRIDDEN_AT,
  TRUE AS IS_ACTIVE
FROM SILVER.STG_MANUAL_STARTUP_REVIEW r
JOIN SILVER.DRM_COMPANY_URLS_VW c
  ON c.DEALROOM_URL_NORM = UTIL.NORMALIZE_DEALROOM_URL(r.DEALROOM_URL)
WHERE LOWER(TRIM(r.STARTUP_STATUS)) IN ('startup','non-startup','for-review');



-- Create an “effective” view that your downstream dashboards/use-cases consume.
CREATE OR REPLACE VIEW SILVER.DRM_STARTUP_CLASSIFICATION_EFFECTIVE_VW AS
WITH latest_override AS (
  SELECT *
  FROM SILVER.DRM_STARTUP_OVERRIDES
  WHERE IS_ACTIVE = TRUE
  QUALIFY ROW_NUMBER() OVER (
    PARTITION BY DEALROOM_ID
    ORDER BY OVERRIDDEN_AT DESC
  ) = 1
)
SELECT
  base.DEALROOM_ID,

  -- effective rating + reason
  COALESCE(o.RATING_LETTER, base.RATING_LETTER) AS RATING_LETTER_EFFECTIVE,
  COALESCE(o.RATING_REASON, base.CLASSIFICATION_REASON) AS RATING_REASON_EFFECTIVE,

  -- effective startup status (keep for-review distinct)
  COALESCE(
    CASE
      WHEN o.STARTUP_STATUS = 'startup'     THEN 'startup'
      WHEN o.STARTUP_STATUS = 'non-startup' THEN 'non_startup'
      WHEN o.STARTUP_STATUS = 'for-review'  THEN 'for_review'
      ELSE NULL
    END,
    base.STARTUP_STATUS
  ) AS STARTUP_STATUS_EFFECTIVE,

  -- keep original fields too
  base.RATING_LETTER AS RATING_LETTER_BASE,
  base.STARTUP_STATUS AS STARTUP_STATUS_BASE,
  base.STARTUP_SCORE,
  base.CONFIDENCE_LEVEL,
  o.OVERRIDDEN_AT,
  o.OVERRIDDEN_BY,
  o.SOURCE
FROM SILVER.DRM_STARTUP_CLASSIFICATION_SILVER base
LEFT JOIN latest_override o
  ON o.DEALROOM_ID = base.DEALROOM_ID;



-- How many overrides inserted?
SELECT STARTUP_STATUS, RATING_LETTER, COUNT(*) N
FROM SILVER.DRM_STARTUP_OVERRIDES
WHERE IS_ACTIVE = TRUE
GROUP BY 1,2
ORDER BY 3 DESC;

-- Effective counts
SELECT STARTUP_STATUS_EFFECTIVE, COUNT(*) N
FROM SILVER.DRM_STARTUP_CLASSIFICATION_EFFECTIVE_VW
GROUP BY 1
ORDER BY 2 DESC;
